controller_list:
  - name: fake_left_arm_controller
    joints:
      - body_to_left_shoulder_joint
      - shoulder_stevo_lift_to_axis
      - big_arm_up_to_axis
      - small_arm_up_to_axis
      - wrist_run_stevo_to_axis
  - name: fake_left_gripper_controller
    joints:
      - hand_run_stevo_to_hand_run_stevo_axis